### ISSUE TITLE
TypeError: can only concatenate tuple (not "float") to tuple

### ISSUE THREAD

**Issue by reborm** [taki0112/UNIT-Tensorflow#3]
Hi, Thank you for your share! I use your code to train on my dataset. After training, when I want to test the model using test images, I got this error. Could you please help solve it?

Total size of variables: 68329736
Total bytes of variables: 273318944
 [*] Reading checkpoints...
 [*] Success to read UNIT.model-101
 [*] Load SUCCESS
Processing A image: ./dataset/face2depth/testA/1.png
Traceback (most recent call last):
  File "main_multi_gpu.py", line 108, in <module>
    main()
  File "main_multi_gpu.py", line 104, in main
    gan.test()
  File "/home/xxx/UNIT-Tensorflow/UNIT_multi_gpu.py", line 481, in test
    save_images(fake_img, [1, 1], image_path)
  File "/home/xxx/UNIT-Tensorflow/utils.py", line 103, in save_images
    return imsave(inverse_transform(images), size, image_path)
  File "/home/xxx/UNIT-Tensorflow/utils.py", line 106, in inverse_transform
    return (images+1.) / 2
TypeError: can only concatenate tuple (not "float") to tuple

**Comment by taki0112** [comment]
sorry
I fix it
